---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stalwart-mail.fullname" . }}
  labels:
    {{- include "stalwart-mail.labels" . | nindent 4 }}
data:
  "config.toml": |
    {{- toToml .Values.config | replace ".0\n" "\n" | nindent 4 }}
