{
 "title": "Stalwart Mail",
 "tags": [ "Mail" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(user_count,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(user_count{namespace=~\"$namespace\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Counts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(user_count{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "Users"
    },
    {
     "expr": "sum(domain_count{namespace=~\"$namespace\",job=~\"$job\"})",
     "legendFormat": "Domain"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(auth_success{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(auth_error{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(increase(auth_failed{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(auth_success{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Success: {{namespace}}-{{job}}"
    },
    {
     "expr": "sum(irate(auth_error{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Error: {{namespace}}-{{job}}"
    },
    {
     "expr": "sum(irate(auth_failed{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Failed: {{namespace}}-{{job}}"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(store_data_read{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Read: {{namespace}}-{{job}}"
    },
    {
     "expr": "sum(irate(store_data_write{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Write: {{namespace}}-{{job}}"
    },
    {
     "expr": "sum(irate(store_data_iterate{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Iterate: {{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Blob",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(store_blob_read{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Read: {{namespace}}-{{job}}"
    },
    {
     "expr": "sum(irate(store_blob_write{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Write: {{namespace}}-{{job}}"
    }
   ]
  },
  { "title": "Delivery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Delivery rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(delivery_attempt_start{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Start: {{namespace}}-{{job}}"
    },
    {
     "expr": "sum(irate(delivery_completed{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Competed: {{namespace}}-{{job}}"
    },
    {
     "expr": "sum(irate(delivery_delivered{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Delivered: {{namespace}}-{{job}}"
    },
    {
     "expr": "sum(irate(delivery_dsn_success{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) without (instance,pod,endpoint,container,service)",
     "legendFormat": "DSN success: {{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Delivery",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(delivery_active_connections{namespace=~\"$namespace\",job=~\"$job\"}) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Active: {{namespace}}-{{job}}"
    },
    {
     "expr": "sum(delivery_attempt_start{namespace=~\"$namespace\",job=~\"$job\"}-delivery_completed{namespace=~\"$namespace\",job=~\"$job\"}) without (instance,pod,endpoint,container,service)",
     "legendFormat": "Not complete: {{namespace}}-{{job}}"
    }
   ]
  },
  {
   "title": "Delivery duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 23 },
   "targets": [
    {
     "expr": "sum(irate(delivery_total_time_bucket{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Failure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Store",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(eval_store_not_found{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Eval not found"
    }
   ]
  },
  {
   "title": "TLS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tls_handshake_error{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Handshake"
    }
   ]
  },
  {
   "title": "Delivery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(delivery_dsn_perm_fail{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "DSN Perm"
    },
    {
     "expr": "sum(increase(delivery_ip_lookup_failed{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "IP Lookup"
    },
    {
     "expr": "sum(increase(delivery_mx_lookup_failed{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "MX Lookup"
    }
   ]
  },
  {
   "title": "SMTP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(smtp_iprev_fail{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "iprev"
    },
    {
     "expr": "sum(increase(smtp_spf_ehlo_fail{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "SPF EHLO"
    },
    {
     "expr": "sum(increase(smtp_spf_from_fail{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "SPF From"
    },
    {
     "expr": "sum(increase(smtp_relay_not_allowed{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Relay not allowed"
    }
   ]
  },
  {
   "title": "SPAM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(spam_classify_error{namespace=~\"$namespace\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Classify"
    }
   ]
  }
 ]
}